import { Resend } from "resend";

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendProductionRecordEmail(record) {
  try {
    await resend.emails.send({
      from: "Ziprus Production <onboarding@resend.dev>",
      to: process.env.ADMIN_EMAIL,
      subject: `🏭 New Production Record - ${record.materialType}`,

      html: `
<!DOCTYPE html>
<html>

<body
  style="
    margin:0;
    padding:40px 20px;
    background:#f4f7f6;
    font-family:Arial, Helvetica, sans-serif;
  "
>

<table
  width="100%"
  cellpadding="0"
  cellspacing="0"
  style="max-width:750px;margin:auto;"
>

<tr>
<td>

<div
  style="
    background:white;
    border-radius:20px;
    overflow:hidden;
    box-shadow:0 15px 40px rgba(0,0,0,0.08);
  "
>

<!-- HEADER -->
<div
  style="
    background:#035145;
    padding:40px;
    text-align:center;
  "
>

<div
  style="
    width:90px;
    height:90px;
    margin:auto;
    border-radius:50%;
    background:rgba(255,255,255,0.15);
    line-height:90px;
    font-size:45px;
  "
>
🏭
</div>

<h1
  style="
    color:white;
    margin-top:20px;
    margin-bottom:10px;
    font-size:30px;
  "
>
Production Record Submitted
</h1>

<p
  style="
    color:#d8f3ea;
    font-size:16px;
    margin:0;
  "
>
A new production record has been submitted by the factory team.
</p>

</div>

<!-- HERO NUMBER -->
<div
  style="
    background:#f7faf9;
    text-align:center;
    padding:35px;
    border-bottom:1px solid #eee;
  "
>

<p
  style="
    margin:0;
    color:#666;
    font-size:14px;
    letter-spacing:1px;
  "
>
TOTAL PRODUCE AMOUNT
</p>

<h2
  style="
    margin:10px 0;
    color:#035145;
    font-size:42px;
  "
>
${Number(record.totalProductionAmount).toLocaleString()}
Naira
</h2>

<p
  style="
    margin:0;
    color:#666;
  "
>
${record.totalProduce} bags × ${record.amountPerBag}N
</p>

</div>

<!-- DETAILS -->
<div style="padding:35px;">

<h2
  style="
    margin-top:0;
    margin-bottom:25px;
    color:#035145;
  "
>
Production Details
</h2>

<table
  width="100%"
  cellpadding="12"
  cellspacing="0"
  style="
    border-collapse:collapse;
    font-size:15px;
  "
>

<tr>
<td
  style="
    background:#f8f8f8;
    width:45%;
    border-bottom:1px solid #eee;
  "
>
📅 Date
</td>

<td
  style="
    border-bottom:1px solid #eee;
  "
>
${record.date}
</td>
</tr>

<tr>
<td
  style="
    background:#f8f8f8;
    border-bottom:1px solid #eee;
  "
>
🕒 Time
</td>

<td
  style="
    border-bottom:1px solid #eee;
  "
>
${record.time}
</td>
</tr>

<tr>
<td
  style="
    background:#f8f8f8;
    border-bottom:1px solid #eee;
  "
>
👷 Worker ID
</td>

<td
  style="
    border-bottom:1px solid #eee;
  "
>
${record.workerId}
</td>
</tr>

<tr>
<td
  style="
    background:#f8f8f8;
    border-bottom:1px solid #eee;
  "
>
🪨 Material
</td>

<td
  style="
    border-bottom:1px solid #eee;
  "
>
${record.materialType}
</td>
</tr>

<tr>
<td
  style="
    background:#f8f8f8;
    border-bottom:1px solid #eee;
  "
>
📦 Total Bags Produced
</td>

<td
  style="
    border-bottom:1px solid #eee;
  "
>
${Number(record.totalProduce).toLocaleString()}
</td>
</tr>

<tr>
<td
  style="
    background:#f8f8f8;
    border-bottom:1px solid #eee;
  "
>
⚖️ Weight Per Bag
</td>

<td
  style="
    border-bottom:1px solid #eee;
  "
>
${Number(record.amountPerBag).toLocaleString()}kg
</td>
</tr>

</table>

${
  record.comment
    ? `
<div
  style="
    margin-top:30px;
    background:#fffaf2;
    padding:25px;
    border-left:6px solid #f59e0b;
    border-radius:12px;
  "
>

<h3
  style="
    margin-top:0;
    color:#b45309;
  "
>
📝 Additional Comment
</h3>

<p
  style="
    margin-bottom:0;
    line-height:1.7;
    color:#444;
  "
>
${record.comment}
</p>

</div>
`
    : ""
}

<div
  style="
    text-align:center;
    margin-top:35px;
  "
>

<a
  href="${process.env.NEXT_PUBLIC_APP_URL}/viewreport/dailyReportsList"
  style="
    display:inline-block;
    background:#035145;
    color:white;
    text-decoration:none;
    padding:15px 30px;
    border-radius:10px;
    font-weight:bold;
    font-size:16px;
  "
>
View Production Dashboard
</a>

</div>

</div>

<!-- FOOTER -->
<div
  style="
    background:#fafafa;
    padding:25px;
    text-align:center;
    border-top:1px solid #eee;
  "
>

<p
  style="
    margin:0;
    color:#666;
    font-size:14px;
  "
>
This notification was automatically generated by
<strong style="color:#035145;">
Ziprus Chemicals Production System
</strong>
</p>

<p
  style="
    margin-top:12px;
    font-size:12px;
    color:#999;
  "
>
© ${new Date().getFullYear()} Ziprus Chemicals Ltd.
</p>

</div>

</div>

</td>
</tr>

</table>

</body>
</html>
      `,
    });
  } catch (error) {
    console.error("Production email error:", error);
  }
}